os: Visual Studio 2017

platform:
  - x64

environment:
  nodejs_version: '12.16.3'
  matrix:
    - npm_config_arch: 'x64'
      TARGET_ARCH: 'x64'
    - npm_config_arch: 'arm64'
      TARGET_ARCH: 'arm64'

cache:
  - '%USERPROFILE%\.electron'
  - .eslintcache
  - '%LOCALAPPDATA%\Yarn\Cache\v4'

skip_tags: true
skip_branch_with_pr: true

version: '{build}'

install:
  - cmd: regedit /s script\default-to-tls12-on-appveyor.reg
  - cmd: set npm_config_arch = %npm_config_arch%
  - cmd: set TARGET_ARCH = %TARGET_ARCH%
  - ps: Install-Product node $env:nodejs_version $env:platform
  - git submodule update --init --recursive
  - yarn install --force

build_script:
  - yarn lint
  - yarn validate-changelog
  - yarn check-modified
  - yarn build:prod

test_script:
  - yarn test:setup
  - cmd: ./script/test-appveyor.bat

on_success:
  - yarn run publish

on_finish:
  - yarn test:review
  - yarn test:report
